### ISSUE TITLE
Cannot convert value "any6" to type "System.Net.IPAddress". Error: "An invalid IP address was specified." 

### ISSUE THREAD

**Issue by wimanx** [net-utilities/BigIPReport#141]
**Describe the bug**
If a VIP is configured with a port-list, BigIPreport stops running

**To Reproduce**
Configure a VIP with a port-list
![port-list](https://github.com/net-utilities/BigIPReport/assets/36816908/00afc83f-b3de-46a4-b9f5-c5fecdeb42c3)

**Config**
_tmsh list ltm virtual /Common/VIP_

ltm virtual VIP-int-sko-multi-vip {
    creation-time 2021-05-26:12:40:14
    ip-protocol tcp
    last-modified-time 2021-08-26:11:38:10
    persist {
        source_addr {
            default yes
        }
    }
    pool VIP-sko-multi-pool
    profiles {
        f5-tcp-lan { }
    }
    serverssl-use-sni disabled
    source-address-translation {
        pool VIP-int-sko-snatpool
        type snat
    }
    traffic-matching-criteria VIP-int-sko-multi-vip_VS_TMC_OBJ
    translate-address enabled
    translate-port enabled
    vs-index 5
}

_list security firewall port-list VIP-int-sko-multi-vip-ports_
security firewall port-list VIP-int-sko-multi-vip-ports {
    ports {
        50006 { }
        60006 { }
    }
}

**Error message**
Unable to cache virtual servers: Cannot convert value "any6" to type "System.Net.IPAddress". Error: "An invalid IP address was specified." (line 1038)

**Additional context**
BigIPReport version 5.6.2

**Comment by epacke** [comment]
We don't currently support port lists right now. That said, the latest version indexed my virtual server successfully. 
Try upgrading to the latest version of BigIPReport?
