### ISSUE TITLE
Sync / standby status for devices

### ISSUE THREAD

**Issue by timriker** [net-utilities/BigIPReport#38]
I don't know if the REST interface shows if device pairs are in sync. it would be nice if the device tab highlighted pairs that are out of sync.

I would also like to see some coloring indication to easily see when B nodes are active and A on standby.

**Comment by Patrik-Netent** [comment]
Really good ideas!

**Comment by epacke** [comment]
Really good ideas!

**Comment by timriker** [comment]
/mgmt/tm/cm/device-group/ gives sync groups (including GTM!) but I don't see the current status.

**Comment by timriker** [comment]
/mgmt/tm/cm/sync-status/ has entries.*.nestedStats.entries.color = green

This might be what's needed? have to deliberately get things out of sync and test more.
