### ISSUE TITLE
Slack webhook support

### ISSUE THREAD

**Issue by epacke** [net-utilities/BigIPReport#48]
## Short
Having Slack webhook support would be a much more modern approach than email.
Suggestion is to save potential alerts in a json file, just like the support state. 

In the case of certificate expiration we could let the user alert toggle alerts on/off per type and configure how many alerts per type+key the report should send (*X hours/days/minutes* per *alertKey*).

The state could be saved in `/json/alerts.json` and we could clean the file from events older than X amount of days at each run.

## Example configuration

```xml

<!--
    The webhook to use when sending Slack alerts
-->

<SlackWebhook>https://slack.webhook.url</SlackWebHook>

<!--
    certificateExpiration
    Description: Have BigIPReport alert when certificates are about to expire
    WaitHoursBetween: How many hours between alerting, per certificate

    dataCollectionError
    Description: Have BigIPReport alert when there is issues connecting to a device
    WaitHoursBetween: How many hours between alerting, per device 
-->

<SlackAlerts>
    <certificateExpiration>
        <Enabled>True</Enabled>
        <WaitHoursBetween>24</WaitHoursBetween>
    </certificateExpiration>
    <dataCollectorError>
        <Enabled>True</Enabled>
        <WaitHoursBetween>4</WaitHoursBetween>
    </dataCollectorError>
</SlackAlerts
```

## Example json data

```json
[
  {
      "type": "certificateExpiration",
      "alertKey": "/Common/my-cert.com",
      "message": "The certificate /Common/my-cert.com is about to expire.",
      "lastAlerted": "1618832177"
  }, {
    "type": "dataCollectorError",
    "alertKey": "myltm.example.com",
    "message": "Failed to get a token from XXXX.",
    "lastAlerted": "1618832177"
  }
]
```

What do you think?

**Comment by timriker** [comment]
We may want to tie this to a log level on the log tab. ie: send slack alerts for verbose, warnings, errors, etc. Similar email setting, send email for warnings, errors, nothing, etc. In any case, log the message to the log tab.

I'd like to see the log tab itself colored to reflect if there were errors in the last run or not.

I'd suggest the same for the certs. If there are expired certs, color it red, nearly expired, yellow, else normal.

**Comment by epacke** [comment]
I would suggest we break off the GUI part to a separate issue and focus on the backend here to keep the scope fairly limited. Will start working on this today as I need to replace an old script that does cert alerts.
