### ISSUE TITLE
Configuration validation - Validation of paths not working

### ISSUE THREAD

**Issue by epacke** [net-utilities/BigIPReport#55]
When testing for missing properties in the config file we test like so:
```
$null -eq <path>
```

This does not seem to work on newer versions of PowerShell. If it ever worked.

**Comment by timriker** [comment]
the code:
`elseif ($null -ne $Location) {`
is not testing the path, it's testing to see if Location was passed in as a parameter. Powershell 6 and earlier did not set the child scripts current working directory to the location the script was located. It might be set to the user's home directory, and it might be set to the powershell.exe directory, but not to the pwd where the script was called from.

We will likely run into this difference again with the modular script unless we pass the current directory in.

**Comment by epacke** [comment]
Updated the issue. Sorry for the bad quality, I just dumped it here since I was busy

**Comment by epacke** [comment]
```
Function Test-ConfigPath {
    Param($XPath)

    $NodeList = $Global:Bigipreportconfig.SelectNodes($XPath)
    Return $NodeList.Count -gt 0
}

# Returns true if the path exists, false if it doesn't
Test-ConfigPath "/Settings/SlackWebhook"
```

This seems to be quite succinct. :)

**Comment by timriker** [comment]
I'm not sure what you're trying to do here. The code I quoted above is not checking for a file path. It's checking if a variable is defined. Where are you looking for a code path? We either read the xml or we don't. Where would this code be needed? I don't understand what this issue is about. I don't see a bug.

**Comment by epacke** [comment]
The bug is that the config validations we run on config file paths. Like testing if settings.ReportRoot exists or not is not always working. The code above allows us to test an XML using an xpath selector to validate that all the configuration file paths are working. 

A user ran into a case with a missing config file property and the script spat out a generic error instead of the intended `The configuration X is missing, please update the configuration file to the latest version`.
