### ISSUE TITLE
Iterate through virtual server and sub-collections

### ISSUE THREAD

**Issue by grf5** [net-utilities/BigIPReport#74]
With larger configurations, polling the /ltm/virtuals endpoint with the &expandSubcollections=true query parameter can result in timeouts. I am seeing this on 14.1.2.6 with ~250 virtual servers, each with various custom profiles, iRules, etc. 

This can typically be alleviated by increasing timeouts using system db values:

https://support.f5.com/csp/article/K94602685 

However, some versions of TMOS do not support those variables (https://cdn.f5.com/product/bugtracker/ID858189.html). Using the $top and $skip query parameters to iterate through each virtual would break up a single giant LTM query into multiple smaller requests for scale. 

https://devcentral.f5.com/s/articles/demystifying-icontrol-rest-part-3-how-to-pass-query-parameters-and-tmsh-options

**Comment by epacke** [comment]
250 virtual servers should be no problem. Is the management provisioning a bit on the small side?

**Comment by evanatuo** [comment]
+1 for iteration. @grf5 beat me to it.

We're experiencing this at around 1350 virtual servers with physical LTMs provisioned with large management (on 14.1.2.6 codebase). The script will complete maybe 1 in 10 times, but mostly fails due to the large request. The problem has become worse over the past few months as the environment grew (from maybe 30% failure to 90% failure). 

I've tried running the REST call directly with a separate tool to rule out an issue in PowerShell, and it does seem to confirm the large request appears to be the root cause of the report failure.

**Comment by epacke** [comment]
Could you please try to iterate through the configuration and see what $top should be at and confirm this is the issue.

I've learned the hard way that v14 is a real resource hog compared to ie. v12 and has to bump the management provisioning to large on most machines.

**Comment by grf5** [comment]
@epacke, thanks for the quick response! I do not believe the virtual count is as important as total object count. I'm running scale testing so each of my virtual servers has a client-ssl, server-ssl, custom http, persistence profile, iRule, etc. In other words, I'm building "Christmas tree" virtual servers. I can certainly test larger configuration sets. In either manner, once the iControl REST call exceeds a certain amount of data, it will hang. I certainly agree that provisioning management to a larger size is the first step (https://support.f5.com/csp/article/K26427018) and this is done in my environment. Aside from all, I certainly appreciate the advice.

**Comment by epacke** [comment]
No problem!

I've had installations with thousand VIPs and a thousand pools. It ran ok there.

That said, there IS a limit, I'm just not sure what it is. 250 should be well below though which makes me suspect something else. Have you poked F5 support? I reckon you should expect their API to be able to handle this amount. 

If anyone can confirm that interating through the configuration works it'd be great.

**Comment by evanatuo** [comment]
@epacke, 

I can confirm I can iterate though and receive expected results:

I've tried $top values from 10, incrementing units of ten up to 100 and these appear to work as expected, longest query was 40s. 

Top value 50 seemed to be a much more comfortable size (18s response) than 100 (40s response) as it's starting to get close to that 60s default timeout.

**Comment by epacke** [comment]
Super, thanks for confirming. I believe this will add quiet a lot of overhead but that's better than no report at all. :)

**Comment by epacke** [comment]
Should also add that running the report on a weak server can incur unexpected timeouts/errors. Might also want to validate memory consumption.

**Comment by timriker** [comment]
When I was testing this a while back it seemed that adding $top and $skip did not avoid the timeouts. The system load seemed to show that the entire list was being created anyway and $top and $skip just limited what was output.

This was on an older version of BIG-IP, but I don't recall what version.

Are you consistently seeing timeouts on the complete request and consistently not getting timeouts on the paged responses?

**Comment by evanatuo** [comment]
@timriker -- My experience thus far is that 9/10 times the complete call will fail, and 10/10 attempts to chunk using $top and $skip have returned successful responses.

**Comment by timriker** [comment]
@evanatuo That sounds good. What chunk size are you using? Is this with the 50 size you were saying performed well?

**Comment by evanatuo** [comment]
@timriker  Yes -- 50 seems to be a happy middle ground for a call, at least in my environment.

I did a minimum of ten, incrementing ten up to 100 per call.

A response with a chunk size of 50 took ~18s to complete while a chunk size of 100 took ~40s which is still "OK" but is getting close to that 60s timeout. To be safer I would keep it at 50. This could always be a configurable item with a default of 50.

**Comment by timriker** [comment]
I added a RestPageSize option and applied this to the two rest calls in a loop. This is in release 5.6.1. You can test from git, or wait for Patrik to review and release a new zip.

**Comment by evanatuo** [comment]
Tested 5.6.1 and this seems to perform much better!

Thank you @timriker and @epacke for your continued effort to support the community. Thanks also to @grf5 for putting the initial issue in.

**Comment by epacke** [comment]
@timriker did all the work. I'm all talk. 😂
Issue closed in PR #76.

Thanks Tim!
