### ISSUE TITLE
contributor guide

### ISSUE THREAD

**Issue by jasonrahm** [net-utilities/BigIPReport#82]
Could you add a brief doc explaining how to contribute? There was an ask in the DC forums to add similar support for GTM objects. No promises, but something I might take a look at.

**Comment by epacke** [comment]
Sure thing! Will fix within a few days.

**Comment by epacke** [comment]
I have not forgotten this. Thought I'd have some time in the week but it just fell apart. We're moving to a new house the 11th of December so I have a feeling I won't have time to fix this until after new year. :(

**Comment by epacke** [comment]
I've written a draft. It's not very detailed but should cover how to add/modify the data sets of BigIPReport. Still waiting for feedback from Tim so I'd advise you to wait until he's given some.

Anyway, here it is:
https://loadbalancing.se/2022/01/19/contributing-to-bigipreport/

Will update here again once we've polished it a bit more.

**Comment by timriker** [comment]
Posted some comments on Discord. Would be nice to explain the single thread test with a bigip on the command line.
Does the npx http-server support brotli? We should document paths that support the brotli files as they are so much faster to load.

**Comment by epacke** [comment]
Updated with how to run a single threaded test.

**Comment by timriker** [comment]
I tried testing with npx http-server, but it crashes for me. Not sure why.

[Thu Jan 20 2022 13:27:11 GMT-0700 (Mountain Standard Time)]  "GET /underlay/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36"
_http_outgoing.js:470
    throw new ERR_HTTP_HEADERS_SENT('set');
    ^

Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:470:11)
    at module.exports.ResponseStream.(anonymous function) [as setHeader] (/home/timr/.npm/_npx/3513/lib/node_modules/http-server/node_modules/union/lib/response-stream.js:100:34)
    at Object.exports.(anonymous function) (/home/timr/.npm/_npx/3513/lib/node_modules/http-server/lib/core/status-handlers.js:57:7)
    at Readable.stream.on (/home/timr/.npm/_npx/3513/lib/node_modules/http-server/lib/core/index.js:339:22)
    at Readable.emit (events.js:198:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by epacke** [comment]
Nice catch, I missed that!

I actually got it working on my Mac:
```patrik@MacBook-Pro underlay % openssl req -newkey rsa:2048 -new -nodes -x509 -days 3650 -keyout key.pem -out cert.pem
... default options until here ...
Common Name (eg, fully qualified host name) []:localhost
patrik@MacBook-Pro underlay % ls
cert.pem	css		images		index.html	js		json		key.pem
patrik@MacBook-Pro underlay % npx http-server -b -S -p 8443 -C ./cert.pem                                            
Starting up http-server, serving ./ through https

http-server version: 14.1.0

http-server settings: 
CORS: disabled
Cache: 3600 seconds
Connection Timeout: 120 seconds
Directory Listings: visible
AutoIndex: visible
Serve GZIP Files: false
Serve Brotli Files: true
Default File Extension: none

Available on:
  https://127.0.0.1:8443
  https://192.168.70.26:8443
Hit CTRL-C to stop the server
```

Then validating via Chrome:
<img width="314" alt="image" src="https://user-images.githubusercontent.com/17186619/150424613-be8c4774-b174-4d97-968e-42e05bbbb154.png">

**Comment by epacke** [comment]
Article updated with the brotli instructions.

**Comment by epacke** [comment]
Closing the issue, feel free to re-open if something is missing. Thanks for the feedback!
